### ISSUE TITLE
Persist navigation tab state on dashboard

### ISSUE THREAD

**Issue by tomaroyal** [SevaShop/sevashop#66]
- Have a global state which stores the state on which the user is on

**Comment by rohanrajpal** [comment]
![Uploading image.png…]()

**Comment by rohanrajpal** [comment]
![image](https://user-images.githubusercontent.com/7023147/107150098-1d1c7000-6982-11eb-872f-5281a8acdc81.png)

**Comment by rohanrajpal** [comment]
https://adamwathan.me/2019/10/17/persistent-layout-patterns-in-nextjs/

**Comment by rohanrajpal** [comment]
https://stackoverflow.com/questions/62115518/persistent-layout-in-next-js-with-typescript-and-hoc

**Comment by rohanrajpal** [comment]
@srijanjain I've figured out how to persist the tab states, now you have to do the following

- read the blog and view the code: https://dev.to/ozanbolel/layout-persistence-in-next-js-107g
- Implement Navbar in `sevashop/layouts/HomeLayout.tsx` like we had before, currently we have a sasta looking navbar 
- A lot of pages now have their UI kinda messed up, fix the UI at those places/components
